/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context } from "@monotonous/types"
import { FieldShieldResolver, ObjectTypeShieldResolver } from "nexus-shield"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Json";
    /**
     * Decimal custom scalar type
     */
    decimal<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Decimal";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Json";
    /**
     * Decimal custom scalar type
     */
    decimal<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Decimal";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BillingPlanCreateInput: { // input type
    billingFrequency: NexusGenEnums['BillingFrequencies']; // BillingFrequencies!
    cost: number; // Int!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BillingPlanOrderByInput: { // input type
    billingFrequency?: NexusGenEnums['SortOrder'] | null; // SortOrder
    cost?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  BillingPlanUncheckedCreateInput: { // input type
    billingFrequency: NexusGenEnums['BillingFrequencies']; // BillingFrequencies!
    cost: number; // Int!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BillingPlanUncheckedUpdateInput: { // input type
    billingFrequency?: NexusGenInputs['EnumBillingFrequenciesFieldUpdateOperationsInput'] | null; // EnumBillingFrequenciesFieldUpdateOperationsInput
    cost?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  BillingPlanUncheckedUpdateManyInput: { // input type
    billingFrequency?: NexusGenInputs['EnumBillingFrequenciesFieldUpdateOperationsInput'] | null; // EnumBillingFrequenciesFieldUpdateOperationsInput
    cost?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  BillingPlanUpdateInput: { // input type
    billingFrequency?: NexusGenInputs['EnumBillingFrequenciesFieldUpdateOperationsInput'] | null; // EnumBillingFrequenciesFieldUpdateOperationsInput
    cost?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  BillingPlanUpdateManyMutationInput: { // input type
    billingFrequency?: NexusGenInputs['EnumBillingFrequenciesFieldUpdateOperationsInput'] | null; // EnumBillingFrequenciesFieldUpdateOperationsInput
    cost?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  BillingPlanWhereInput: { // input type
    AND?: Array<NexusGenInputs['BillingPlanWhereInput'] | null> | null; // [BillingPlanWhereInput]
    NOT?: Array<NexusGenInputs['BillingPlanWhereInput'] | null> | null; // [BillingPlanWhereInput]
    OR?: Array<NexusGenInputs['BillingPlanWhereInput'] | null> | null; // [BillingPlanWhereInput]
    billingFrequency?: NexusGenInputs['EnumBillingFrequenciesFilter'] | null; // EnumBillingFrequenciesFilter
    cost?: NexusGenInputs['IntFilter'] | null; // IntFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  BillingPlanWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  EmailConfirmationCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    token: string; // String!
    user: NexusGenInputs['UserCreateNestedOneWithoutEmailConfirmationInput']; // UserCreateNestedOneWithoutEmailConfirmationInput!
  }
  EmailConfirmationCreateNestedOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['EmailConfirmationWhereUniqueInput'] | null; // EmailConfirmationWhereUniqueInput
    connectOrCreate?: NexusGenInputs['EmailConfirmationCreateOrConnectWithoutUserInput'] | null; // EmailConfirmationCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['EmailConfirmationUncheckedCreateWithoutUserInput'] | null; // EmailConfirmationUncheckedCreateWithoutUserInput
  }
  EmailConfirmationCreateOrConnectWithoutUserInput: { // input type
    create: NexusGenInputs['EmailConfirmationUncheckedCreateWithoutUserInput']; // EmailConfirmationUncheckedCreateWithoutUserInput!
    where: NexusGenInputs['EmailConfirmationWhereUniqueInput']; // EmailConfirmationWhereUniqueInput!
  }
  EmailConfirmationCreateWithoutUserInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    token: string; // String!
  }
  EmailConfirmationOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    token?: NexusGenEnums['SortOrder'] | null; // SortOrder
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  EmailConfirmationRelationFilter: { // input type
    is?: NexusGenInputs['EmailConfirmationWhereInput'] | null; // EmailConfirmationWhereInput
    isNot?: NexusGenInputs['EmailConfirmationWhereInput'] | null; // EmailConfirmationWhereInput
  }
  EmailConfirmationUncheckedCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    token: string; // String!
    userId: string; // String!
  }
  EmailConfirmationUncheckedCreateNestedOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['EmailConfirmationWhereUniqueInput'] | null; // EmailConfirmationWhereUniqueInput
    connectOrCreate?: NexusGenInputs['EmailConfirmationCreateOrConnectWithoutUserInput'] | null; // EmailConfirmationCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['EmailConfirmationUncheckedCreateWithoutUserInput'] | null; // EmailConfirmationUncheckedCreateWithoutUserInput
  }
  EmailConfirmationUncheckedCreateWithoutUserInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    token: string; // String!
  }
  EmailConfirmationUncheckedUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    userId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  EmailConfirmationUncheckedUpdateManyInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    userId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  EmailConfirmationUncheckedUpdateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['EmailConfirmationWhereUniqueInput'] | null; // EmailConfirmationWhereUniqueInput
    connectOrCreate?: NexusGenInputs['EmailConfirmationCreateOrConnectWithoutUserInput'] | null; // EmailConfirmationCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['EmailConfirmationUncheckedCreateWithoutUserInput'] | null; // EmailConfirmationUncheckedCreateWithoutUserInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['EmailConfirmationUncheckedUpdateWithoutUserInput'] | null; // EmailConfirmationUncheckedUpdateWithoutUserInput
    upsert?: NexusGenInputs['EmailConfirmationUpsertWithoutUserInput'] | null; // EmailConfirmationUpsertWithoutUserInput
  }
  EmailConfirmationUncheckedUpdateWithoutUserInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  EmailConfirmationUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    user?: NexusGenInputs['UserUpdateOneRequiredWithoutEmailConfirmationInput'] | null; // UserUpdateOneRequiredWithoutEmailConfirmationInput
  }
  EmailConfirmationUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  EmailConfirmationUpdateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['EmailConfirmationWhereUniqueInput'] | null; // EmailConfirmationWhereUniqueInput
    connectOrCreate?: NexusGenInputs['EmailConfirmationCreateOrConnectWithoutUserInput'] | null; // EmailConfirmationCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['EmailConfirmationUncheckedCreateWithoutUserInput'] | null; // EmailConfirmationUncheckedCreateWithoutUserInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['EmailConfirmationUncheckedUpdateWithoutUserInput'] | null; // EmailConfirmationUncheckedUpdateWithoutUserInput
    upsert?: NexusGenInputs['EmailConfirmationUpsertWithoutUserInput'] | null; // EmailConfirmationUpsertWithoutUserInput
  }
  EmailConfirmationUpdateWithoutUserInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  EmailConfirmationUpsertWithoutUserInput: { // input type
    create: NexusGenInputs['EmailConfirmationUncheckedCreateWithoutUserInput']; // EmailConfirmationUncheckedCreateWithoutUserInput!
    update: NexusGenInputs['EmailConfirmationUncheckedUpdateWithoutUserInput']; // EmailConfirmationUncheckedUpdateWithoutUserInput!
  }
  EmailConfirmationWhereInput: { // input type
    AND?: Array<NexusGenInputs['EmailConfirmationWhereInput'] | null> | null; // [EmailConfirmationWhereInput]
    NOT?: Array<NexusGenInputs['EmailConfirmationWhereInput'] | null> | null; // [EmailConfirmationWhereInput]
    OR?: Array<NexusGenInputs['EmailConfirmationWhereInput'] | null> | null; // [EmailConfirmationWhereInput]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    token?: NexusGenInputs['StringFilter'] | null; // StringFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  EmailConfirmationWhereUniqueInput: { // input type
    token?: string | null; // String
    userId?: string | null; // String
  }
  EnumBillingFrequenciesFieldUpdateOperationsInput: { // input type
    set?: NexusGenEnums['BillingFrequencies'] | null; // BillingFrequencies
  }
  EnumBillingFrequenciesFilter: { // input type
    equals?: NexusGenEnums['BillingFrequencies'] | null; // BillingFrequencies
    in?: Array<NexusGenEnums['BillingFrequencies'] | null> | null; // [BillingFrequencies]
    not?: NexusGenInputs['NestedEnumBillingFrequenciesFilter'] | null; // NestedEnumBillingFrequenciesFilter
    notIn?: Array<NexusGenEnums['BillingFrequencies'] | null> | null; // [BillingFrequencies]
  }
  IntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  NestedEnumBillingFrequenciesFilter: { // input type
    equals?: NexusGenEnums['BillingFrequencies'] | null; // BillingFrequencies
    in?: Array<NexusGenEnums['BillingFrequencies'] | null> | null; // [BillingFrequencies]
    not?: NexusGenInputs['NestedEnumBillingFrequenciesFilter'] | null; // NestedEnumBillingFrequenciesFilter
    notIn?: Array<NexusGenEnums['BillingFrequencies'] | null> | null; // [BillingFrequencies]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  RegisterInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  UserCreateInput: { // input type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    emailConfirmation?: NexusGenInputs['EmailConfirmationCreateNestedOneWithoutUserInput'] | null; // EmailConfirmationCreateNestedOneWithoutUserInput
    id?: string | null; // String
    profile?: NexusGenInputs['UserProfileCreateNestedOneWithoutUserInput'] | null; // UserProfileCreateNestedOneWithoutUserInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserCreateNestedOneWithoutEmailConfirmationInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutEmailConfirmationInput'] | null; // UserCreateOrConnectWithoutEmailConfirmationInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutEmailConfirmationInput'] | null; // UserUncheckedCreateWithoutEmailConfirmationInput
  }
  UserCreateNestedOneWithoutProfileInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutProfileInput'] | null; // UserCreateOrConnectWithoutProfileInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutProfileInput'] | null; // UserUncheckedCreateWithoutProfileInput
  }
  UserCreateOrConnectWithoutEmailConfirmationInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutEmailConfirmationInput']; // UserUncheckedCreateWithoutEmailConfirmationInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateOrConnectWithoutProfileInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutProfileInput']; // UserUncheckedCreateWithoutProfileInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutEmailConfirmationInput: { // input type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    id?: string | null; // String
    profile?: NexusGenInputs['UserProfileCreateNestedOneWithoutUserInput'] | null; // UserProfileCreateNestedOneWithoutUserInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserCreateWithoutProfileInput: { // input type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    emailConfirmation?: NexusGenInputs['EmailConfirmationCreateNestedOneWithoutUserInput'] | null; // EmailConfirmationCreateNestedOneWithoutUserInput
    id?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserOrderByInput: { // input type
    confirmed?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    emailConfirmation?: NexusGenInputs['EmailConfirmationOrderByInput'] | null; // EmailConfirmationOrderByInput
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    profile?: NexusGenInputs['UserProfileOrderByInput'] | null; // UserProfileOrderByInput
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserProfileCreateInput: { // input type
    firstName: string; // String!
    id?: string | null; // String
    lastName: string; // String!
    user: NexusGenInputs['UserCreateNestedOneWithoutProfileInput']; // UserCreateNestedOneWithoutProfileInput!
  }
  UserProfileCreateNestedOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['UserProfileWhereUniqueInput'] | null; // UserProfileWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserProfileCreateOrConnectWithoutUserInput'] | null; // UserProfileCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['UserProfileUncheckedCreateWithoutUserInput'] | null; // UserProfileUncheckedCreateWithoutUserInput
  }
  UserProfileCreateOrConnectWithoutUserInput: { // input type
    create: NexusGenInputs['UserProfileUncheckedCreateWithoutUserInput']; // UserProfileUncheckedCreateWithoutUserInput!
    where: NexusGenInputs['UserProfileWhereUniqueInput']; // UserProfileWhereUniqueInput!
  }
  UserProfileCreateWithoutUserInput: { // input type
    firstName: string; // String!
    id?: string | null; // String
    lastName: string; // String!
  }
  UserProfileOrderByInput: { // input type
    firstName?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    lastName?: NexusGenEnums['SortOrder'] | null; // SortOrder
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserProfileRelationFilter: { // input type
    is?: NexusGenInputs['UserProfileWhereInput'] | null; // UserProfileWhereInput
    isNot?: NexusGenInputs['UserProfileWhereInput'] | null; // UserProfileWhereInput
  }
  UserProfileUncheckedCreateInput: { // input type
    firstName: string; // String!
    id?: string | null; // String
    lastName: string; // String!
    userId: string; // String!
  }
  UserProfileUncheckedCreateNestedOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['UserProfileWhereUniqueInput'] | null; // UserProfileWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserProfileCreateOrConnectWithoutUserInput'] | null; // UserProfileCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['UserProfileUncheckedCreateWithoutUserInput'] | null; // UserProfileUncheckedCreateWithoutUserInput
  }
  UserProfileUncheckedCreateWithoutUserInput: { // input type
    firstName: string; // String!
    id?: string | null; // String
    lastName: string; // String!
  }
  UserProfileUncheckedUpdateInput: { // input type
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    userId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserProfileUncheckedUpdateManyInput: { // input type
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    userId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserProfileUncheckedUpdateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['UserProfileWhereUniqueInput'] | null; // UserProfileWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserProfileCreateOrConnectWithoutUserInput'] | null; // UserProfileCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['UserProfileUncheckedCreateWithoutUserInput'] | null; // UserProfileUncheckedCreateWithoutUserInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['UserProfileUncheckedUpdateWithoutUserInput'] | null; // UserProfileUncheckedUpdateWithoutUserInput
    upsert?: NexusGenInputs['UserProfileUpsertWithoutUserInput'] | null; // UserProfileUpsertWithoutUserInput
  }
  UserProfileUncheckedUpdateWithoutUserInput: { // input type
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserProfileUpdateInput: { // input type
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    user?: NexusGenInputs['UserUpdateOneRequiredWithoutProfileInput'] | null; // UserUpdateOneRequiredWithoutProfileInput
  }
  UserProfileUpdateManyMutationInput: { // input type
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserProfileUpdateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['UserProfileWhereUniqueInput'] | null; // UserProfileWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserProfileCreateOrConnectWithoutUserInput'] | null; // UserProfileCreateOrConnectWithoutUserInput
    create?: NexusGenInputs['UserProfileUncheckedCreateWithoutUserInput'] | null; // UserProfileUncheckedCreateWithoutUserInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['UserProfileUncheckedUpdateWithoutUserInput'] | null; // UserProfileUncheckedUpdateWithoutUserInput
    upsert?: NexusGenInputs['UserProfileUpsertWithoutUserInput'] | null; // UserProfileUpsertWithoutUserInput
  }
  UserProfileUpdateWithoutUserInput: { // input type
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  UserProfileUpsertWithoutUserInput: { // input type
    create: NexusGenInputs['UserProfileUncheckedCreateWithoutUserInput']; // UserProfileUncheckedCreateWithoutUserInput!
    update: NexusGenInputs['UserProfileUncheckedUpdateWithoutUserInput']; // UserProfileUncheckedUpdateWithoutUserInput!
  }
  UserProfileWhereInput: { // input type
    AND?: Array<NexusGenInputs['UserProfileWhereInput'] | null> | null; // [UserProfileWhereInput]
    NOT?: Array<NexusGenInputs['UserProfileWhereInput'] | null> | null; // [UserProfileWhereInput]
    OR?: Array<NexusGenInputs['UserProfileWhereInput'] | null> | null; // [UserProfileWhereInput]
    firstName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    lastName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  UserProfileWhereUniqueInput: { // input type
    id?: string | null; // String
    userId?: string | null; // String
  }
  UserRelationFilter: { // input type
    is?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    isNot?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
  }
  UserUncheckedCreateInput: { // input type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    emailConfirmation?: NexusGenInputs['EmailConfirmationUncheckedCreateNestedOneWithoutUserInput'] | null; // EmailConfirmationUncheckedCreateNestedOneWithoutUserInput
    id?: string | null; // String
    profile?: NexusGenInputs['UserProfileUncheckedCreateNestedOneWithoutUserInput'] | null; // UserProfileUncheckedCreateNestedOneWithoutUserInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserUncheckedCreateWithoutEmailConfirmationInput: { // input type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    id?: string | null; // String
    profile?: NexusGenInputs['UserProfileUncheckedCreateNestedOneWithoutUserInput'] | null; // UserProfileUncheckedCreateNestedOneWithoutUserInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserUncheckedCreateWithoutProfileInput: { // input type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    emailConfirmation?: NexusGenInputs['EmailConfirmationUncheckedCreateNestedOneWithoutUserInput'] | null; // EmailConfirmationUncheckedCreateNestedOneWithoutUserInput
    id?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserUncheckedUpdateInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    emailConfirmation?: NexusGenInputs['EmailConfirmationUncheckedUpdateOneWithoutUserInput'] | null; // EmailConfirmationUncheckedUpdateOneWithoutUserInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    profile?: NexusGenInputs['UserProfileUncheckedUpdateOneWithoutUserInput'] | null; // UserProfileUncheckedUpdateOneWithoutUserInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUncheckedUpdateManyInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUncheckedUpdateWithoutEmailConfirmationInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    profile?: NexusGenInputs['UserProfileUncheckedUpdateOneWithoutUserInput'] | null; // UserProfileUncheckedUpdateOneWithoutUserInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUncheckedUpdateWithoutProfileInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    emailConfirmation?: NexusGenInputs['EmailConfirmationUncheckedUpdateOneWithoutUserInput'] | null; // EmailConfirmationUncheckedUpdateOneWithoutUserInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    emailConfirmation?: NexusGenInputs['EmailConfirmationUpdateOneWithoutUserInput'] | null; // EmailConfirmationUpdateOneWithoutUserInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    profile?: NexusGenInputs['UserProfileUpdateOneWithoutUserInput'] | null; // UserProfileUpdateOneWithoutUserInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateManyMutationInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateOneRequiredWithoutEmailConfirmationInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutEmailConfirmationInput'] | null; // UserCreateOrConnectWithoutEmailConfirmationInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutEmailConfirmationInput'] | null; // UserUncheckedCreateWithoutEmailConfirmationInput
    update?: NexusGenInputs['UserUncheckedUpdateWithoutEmailConfirmationInput'] | null; // UserUncheckedUpdateWithoutEmailConfirmationInput
    upsert?: NexusGenInputs['UserUpsertWithoutEmailConfirmationInput'] | null; // UserUpsertWithoutEmailConfirmationInput
  }
  UserUpdateOneRequiredWithoutProfileInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutProfileInput'] | null; // UserCreateOrConnectWithoutProfileInput
    create?: NexusGenInputs['UserUncheckedCreateWithoutProfileInput'] | null; // UserUncheckedCreateWithoutProfileInput
    update?: NexusGenInputs['UserUncheckedUpdateWithoutProfileInput'] | null; // UserUncheckedUpdateWithoutProfileInput
    upsert?: NexusGenInputs['UserUpsertWithoutProfileInput'] | null; // UserUpsertWithoutProfileInput
  }
  UserUpdateWithoutEmailConfirmationInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    profile?: NexusGenInputs['UserProfileUpdateOneWithoutUserInput'] | null; // UserProfileUpdateOneWithoutUserInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateWithoutProfileInput: { // input type
    confirmed?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    emailConfirmation?: NexusGenInputs['EmailConfirmationUpdateOneWithoutUserInput'] | null; // EmailConfirmationUpdateOneWithoutUserInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpsertWithoutEmailConfirmationInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutEmailConfirmationInput']; // UserUncheckedCreateWithoutEmailConfirmationInput!
    update: NexusGenInputs['UserUncheckedUpdateWithoutEmailConfirmationInput']; // UserUncheckedUpdateWithoutEmailConfirmationInput!
  }
  UserUpsertWithoutProfileInput: { // input type
    create: NexusGenInputs['UserUncheckedCreateWithoutProfileInput']; // UserUncheckedCreateWithoutProfileInput!
    update: NexusGenInputs['UserUncheckedUpdateWithoutProfileInput']; // UserUncheckedUpdateWithoutProfileInput!
  }
  UserWhereInput: { // input type
    AND?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    NOT?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    OR?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    confirmed?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    emailConfirmation?: NexusGenInputs['EmailConfirmationWhereInput'] | null; // EmailConfirmationWhereInput
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    profile?: NexusGenInputs['UserProfileWhereInput'] | null; // UserProfileWhereInput
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: string | null; // String
  }
}

export interface NexusGenEnums {
  BillingFrequencies: "ANNUALLY" | "MONTHLY"
  BillingPlanScalarFieldEnum: "billingFrequency" | "cost" | "createdAt" | "id" | "name" | "updatedAt"
  EmailConfirmationScalarFieldEnum: "createdAt" | "token" | "userId"
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
  UserProfileScalarFieldEnum: "firstName" | "id" | "lastName" | "userId"
  UserScalarFieldEnum: "confirmed" | "createdAt" | "email" | "id" | "updatedAt"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  Decimal: any
  Json: any
}

export interface NexusGenObjects {
  AggregateBillingPlan: { // root type
    avg?: NexusGenRootTypes['BillingPlanAvgAggregateOutputType'] | null; // BillingPlanAvgAggregateOutputType
    count?: NexusGenRootTypes['BillingPlanCountAggregateOutputType'] | null; // BillingPlanCountAggregateOutputType
    max?: NexusGenRootTypes['BillingPlanMaxAggregateOutputType'] | null; // BillingPlanMaxAggregateOutputType
    min?: NexusGenRootTypes['BillingPlanMinAggregateOutputType'] | null; // BillingPlanMinAggregateOutputType
    sum?: NexusGenRootTypes['BillingPlanSumAggregateOutputType'] | null; // BillingPlanSumAggregateOutputType
  }
  AggregateEmailConfirmation: { // root type
    count?: NexusGenRootTypes['EmailConfirmationCountAggregateOutputType'] | null; // EmailConfirmationCountAggregateOutputType
    max?: NexusGenRootTypes['EmailConfirmationMaxAggregateOutputType'] | null; // EmailConfirmationMaxAggregateOutputType
    min?: NexusGenRootTypes['EmailConfirmationMinAggregateOutputType'] | null; // EmailConfirmationMinAggregateOutputType
  }
  AggregateUser: { // root type
    count?: NexusGenRootTypes['UserCountAggregateOutputType'] | null; // UserCountAggregateOutputType
    max?: NexusGenRootTypes['UserMaxAggregateOutputType'] | null; // UserMaxAggregateOutputType
    min?: NexusGenRootTypes['UserMinAggregateOutputType'] | null; // UserMinAggregateOutputType
  }
  AggregateUserProfile: { // root type
    count?: NexusGenRootTypes['UserProfileCountAggregateOutputType'] | null; // UserProfileCountAggregateOutputType
    max?: NexusGenRootTypes['UserProfileMaxAggregateOutputType'] | null; // UserProfileMaxAggregateOutputType
    min?: NexusGenRootTypes['UserProfileMinAggregateOutputType'] | null; // UserProfileMinAggregateOutputType
  }
  BatchPayload: { // root type
    count: number; // Int!
  }
  BillingPlanAvgAggregateOutputType: { // root type
    cost: number; // Float!
  }
  BillingPlanCountAggregateOutputType: { // root type
    _all: number; // Int!
    billingFrequency?: number | null; // Int
    cost: number; // Int!
    createdAt?: number | null; // Int
    id?: number | null; // Int
    name?: number | null; // Int
    updatedAt?: number | null; // Int
  }
  BillingPlanMaxAggregateOutputType: { // root type
    billingFrequency?: NexusGenEnums['BillingFrequencies'] | null; // BillingFrequencies
    cost: number; // Int!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BillingPlanMinAggregateOutputType: { // root type
    billingFrequency?: NexusGenEnums['BillingFrequencies'] | null; // BillingFrequencies
    cost: number; // Int!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BillingPlanSumAggregateOutputType: { // root type
    cost: number; // Int!
  }
  EmailConfirmationCountAggregateOutputType: { // root type
    _all: number; // Int!
    createdAt?: number | null; // Int
    token?: number | null; // Int
    userId?: number | null; // Int
  }
  EmailConfirmationMaxAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    token?: string | null; // String
    userId?: string | null; // String
  }
  EmailConfirmationMinAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    token?: string | null; // String
    userId?: string | null; // String
  }
  Mutation: {};
  Query: {};
  SuccessResponse: { // root type
    success: boolean; // Boolean!
  }
  User: { // root type
    confirmed: boolean; // Boolean!
    email: string; // String!
    id: string; // ID!
    profile?: NexusGenRootTypes['UserProfile'] | null; // UserProfile
  }
  UserCountAggregateOutputType: { // root type
    _all: number; // Int!
    confirmed?: number | null; // Int
    createdAt?: number | null; // Int
    email?: number | null; // Int
    id?: number | null; // Int
    updatedAt?: number | null; // Int
  }
  UserMaxAggregateOutputType: { // root type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    id?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserMinAggregateOutputType: { // root type
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    id?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserProfile: { // root type
    firstName: string; // String!
    id: string; // ID!
    lastName: string; // String!
  }
  UserProfileCountAggregateOutputType: { // root type
    _all: number; // Int!
    firstName?: number | null; // Int
    id?: number | null; // Int
    lastName?: number | null; // Int
    userId?: number | null; // Int
  }
  UserProfileMaxAggregateOutputType: { // root type
    firstName?: string | null; // String
    id?: string | null; // String
    lastName?: string | null; // String
    userId?: string | null; // String
  }
  UserProfileMinAggregateOutputType: { // root type
    firstName?: string | null; // String
    id?: string | null; // String
    lastName?: string | null; // String
    userId?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AggregateBillingPlan: { // field return type
    avg: NexusGenRootTypes['BillingPlanAvgAggregateOutputType'] | null; // BillingPlanAvgAggregateOutputType
    count: NexusGenRootTypes['BillingPlanCountAggregateOutputType'] | null; // BillingPlanCountAggregateOutputType
    max: NexusGenRootTypes['BillingPlanMaxAggregateOutputType'] | null; // BillingPlanMaxAggregateOutputType
    min: NexusGenRootTypes['BillingPlanMinAggregateOutputType'] | null; // BillingPlanMinAggregateOutputType
    sum: NexusGenRootTypes['BillingPlanSumAggregateOutputType'] | null; // BillingPlanSumAggregateOutputType
  }
  AggregateEmailConfirmation: { // field return type
    count: NexusGenRootTypes['EmailConfirmationCountAggregateOutputType'] | null; // EmailConfirmationCountAggregateOutputType
    max: NexusGenRootTypes['EmailConfirmationMaxAggregateOutputType'] | null; // EmailConfirmationMaxAggregateOutputType
    min: NexusGenRootTypes['EmailConfirmationMinAggregateOutputType'] | null; // EmailConfirmationMinAggregateOutputType
  }
  AggregateUser: { // field return type
    count: NexusGenRootTypes['UserCountAggregateOutputType'] | null; // UserCountAggregateOutputType
    max: NexusGenRootTypes['UserMaxAggregateOutputType'] | null; // UserMaxAggregateOutputType
    min: NexusGenRootTypes['UserMinAggregateOutputType'] | null; // UserMinAggregateOutputType
  }
  AggregateUserProfile: { // field return type
    count: NexusGenRootTypes['UserProfileCountAggregateOutputType'] | null; // UserProfileCountAggregateOutputType
    max: NexusGenRootTypes['UserProfileMaxAggregateOutputType'] | null; // UserProfileMaxAggregateOutputType
    min: NexusGenRootTypes['UserProfileMinAggregateOutputType'] | null; // UserProfileMinAggregateOutputType
  }
  BatchPayload: { // field return type
    count: number; // Int!
  }
  BillingPlanAvgAggregateOutputType: { // field return type
    cost: number; // Float!
  }
  BillingPlanCountAggregateOutputType: { // field return type
    _all: number; // Int!
    billingFrequency: number | null; // Int
    cost: number; // Int!
    createdAt: number | null; // Int
    id: number | null; // Int
    name: number | null; // Int
    updatedAt: number | null; // Int
  }
  BillingPlanMaxAggregateOutputType: { // field return type
    billingFrequency: NexusGenEnums['BillingFrequencies'] | null; // BillingFrequencies
    cost: number; // Int!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string | null; // String
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BillingPlanMinAggregateOutputType: { // field return type
    billingFrequency: NexusGenEnums['BillingFrequencies'] | null; // BillingFrequencies
    cost: number; // Int!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string | null; // String
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BillingPlanSumAggregateOutputType: { // field return type
    cost: number; // Int!
  }
  EmailConfirmationCountAggregateOutputType: { // field return type
    _all: number; // Int!
    createdAt: number | null; // Int
    token: number | null; // Int
    userId: number | null; // Int
  }
  EmailConfirmationMaxAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    token: string | null; // String
    userId: string | null; // String
  }
  EmailConfirmationMinAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    token: string | null; // String
    userId: string | null; // String
  }
  Mutation: { // field return type
    confirmEmail: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['User'] | null; // User
    register: NexusGenRootTypes['User'] | null; // User
    requestLogin: NexusGenRootTypes['SuccessResponse'] | null; // SuccessResponse
  }
  Query: { // field return type
    me: NexusGenRootTypes['User'] | null; // User
  }
  SuccessResponse: { // field return type
    success: boolean; // Boolean!
  }
  User: { // field return type
    confirmed: boolean; // Boolean!
    email: string; // String!
    id: string; // ID!
    profile: NexusGenRootTypes['UserProfile'] | null; // UserProfile
  }
  UserCountAggregateOutputType: { // field return type
    _all: number; // Int!
    confirmed: number | null; // Int
    createdAt: number | null; // Int
    email: number | null; // Int
    id: number | null; // Int
    updatedAt: number | null; // Int
  }
  UserMaxAggregateOutputType: { // field return type
    confirmed: boolean | null; // Boolean
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    id: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserMinAggregateOutputType: { // field return type
    confirmed: boolean | null; // Boolean
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    id: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserProfile: { // field return type
    firstName: string; // String!
    fullName: string; // String!
    id: string; // ID!
    lastName: string; // String!
  }
  UserProfileCountAggregateOutputType: { // field return type
    _all: number; // Int!
    firstName: number | null; // Int
    id: number | null; // Int
    lastName: number | null; // Int
    userId: number | null; // Int
  }
  UserProfileMaxAggregateOutputType: { // field return type
    firstName: string | null; // String
    id: string | null; // String
    lastName: string | null; // String
    userId: string | null; // String
  }
  UserProfileMinAggregateOutputType: { // field return type
    firstName: string | null; // String
    id: string | null; // String
    lastName: string | null; // String
    userId: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  AggregateBillingPlan: { // field return type name
    avg: 'BillingPlanAvgAggregateOutputType'
    count: 'BillingPlanCountAggregateOutputType'
    max: 'BillingPlanMaxAggregateOutputType'
    min: 'BillingPlanMinAggregateOutputType'
    sum: 'BillingPlanSumAggregateOutputType'
  }
  AggregateEmailConfirmation: { // field return type name
    count: 'EmailConfirmationCountAggregateOutputType'
    max: 'EmailConfirmationMaxAggregateOutputType'
    min: 'EmailConfirmationMinAggregateOutputType'
  }
  AggregateUser: { // field return type name
    count: 'UserCountAggregateOutputType'
    max: 'UserMaxAggregateOutputType'
    min: 'UserMinAggregateOutputType'
  }
  AggregateUserProfile: { // field return type name
    count: 'UserProfileCountAggregateOutputType'
    max: 'UserProfileMaxAggregateOutputType'
    min: 'UserProfileMinAggregateOutputType'
  }
  BatchPayload: { // field return type name
    count: 'Int'
  }
  BillingPlanAvgAggregateOutputType: { // field return type name
    cost: 'Float'
  }
  BillingPlanCountAggregateOutputType: { // field return type name
    _all: 'Int'
    billingFrequency: 'Int'
    cost: 'Int'
    createdAt: 'Int'
    id: 'Int'
    name: 'Int'
    updatedAt: 'Int'
  }
  BillingPlanMaxAggregateOutputType: { // field return type name
    billingFrequency: 'BillingFrequencies'
    cost: 'Int'
    createdAt: 'DateTime'
    id: 'String'
    name: 'String'
    updatedAt: 'DateTime'
  }
  BillingPlanMinAggregateOutputType: { // field return type name
    billingFrequency: 'BillingFrequencies'
    cost: 'Int'
    createdAt: 'DateTime'
    id: 'String'
    name: 'String'
    updatedAt: 'DateTime'
  }
  BillingPlanSumAggregateOutputType: { // field return type name
    cost: 'Int'
  }
  EmailConfirmationCountAggregateOutputType: { // field return type name
    _all: 'Int'
    createdAt: 'Int'
    token: 'Int'
    userId: 'Int'
  }
  EmailConfirmationMaxAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    token: 'String'
    userId: 'String'
  }
  EmailConfirmationMinAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    token: 'String'
    userId: 'String'
  }
  Mutation: { // field return type name
    confirmEmail: 'User'
    login: 'User'
    register: 'User'
    requestLogin: 'SuccessResponse'
  }
  Query: { // field return type name
    me: 'User'
  }
  SuccessResponse: { // field return type name
    success: 'Boolean'
  }
  User: { // field return type name
    confirmed: 'Boolean'
    email: 'String'
    id: 'ID'
    profile: 'UserProfile'
  }
  UserCountAggregateOutputType: { // field return type name
    _all: 'Int'
    confirmed: 'Int'
    createdAt: 'Int'
    email: 'Int'
    id: 'Int'
    updatedAt: 'Int'
  }
  UserMaxAggregateOutputType: { // field return type name
    confirmed: 'Boolean'
    createdAt: 'DateTime'
    email: 'String'
    id: 'String'
    updatedAt: 'DateTime'
  }
  UserMinAggregateOutputType: { // field return type name
    confirmed: 'Boolean'
    createdAt: 'DateTime'
    email: 'String'
    id: 'String'
    updatedAt: 'DateTime'
  }
  UserProfile: { // field return type name
    firstName: 'String'
    fullName: 'String'
    id: 'ID'
    lastName: 'String'
  }
  UserProfileCountAggregateOutputType: { // field return type name
    _all: 'Int'
    firstName: 'Int'
    id: 'Int'
    lastName: 'Int'
    userId: 'Int'
  }
  UserProfileMaxAggregateOutputType: { // field return type name
    firstName: 'String'
    id: 'String'
    lastName: 'String'
    userId: 'String'
  }
  UserProfileMinAggregateOutputType: { // field return type name
    firstName: 'String'
    id: 'String'
    lastName: 'String'
    userId: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    confirmEmail: { // args
      email: string; // String!
      firstName: string; // String!
      lastName: string; // String!
      token: string; // String!
    }
    login: { // args
      code: string; // String!
    }
    register: { // args
      email: string; // String!
      firstName: string; // String!
      lastName: string; // String!
    }
    requestLogin: { // args
      email: string; // String!
    }
  }
  Query: {
    me: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
    /**
     * Default authorization rule to execute on all fields of this object
     */
    shield?: ObjectTypeShieldResolver<TypeName>
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Authorization rule to execute for this field
     */
    shield?: FieldShieldResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}